# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6266aef5ac9e2d4d42ca320ba6f32a87e87496110a6e0efec0fdf55c5c16b88bd3b541af0c56004a5784588f897bf1a829ef348c67c5009bb6095701d8aede6

test:
  secret_key_base: ae74baf75dd4a4485920353fdfffe5c9002a649033809e389018fb837f1a17437303e767df83a899cd4e2f8d23dc3e762c7fe18e4ae17d573710cd48d5e83329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
